// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPfMF-DZ6_BTNx2ygn_Q87ZQ1I4GXInY',
    appId: '1:591198861834:web:1b62aee2f10e1229f17df3',
    messagingSenderId: '591198861834',
    projectId: 'phf-app-dcbe8',
    authDomain: 'phf-app-dcbe8.firebaseapp.com',
    storageBucket: 'phf-app-dcbe8.firebasestorage.app',
    measurementId: 'G-PBDDNT231T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCBmNOy8x4Xi4GtwzGc5QG8HqjY17jw_I',
    appId: '1:591198861834:android:a94c7f176f869aaef17df3',
    messagingSenderId: '591198861834',
    projectId: 'phf-app-dcbe8',
    storageBucket: 'phf-app-dcbe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwUFP0f3vCWU0C1rNqkKmfr-WG0IzIVX8',
    appId: '1:591198861834:ios:f71064d24a6af1edf17df3',
    messagingSenderId: '591198861834',
    projectId: 'phf-app-dcbe8',
    storageBucket: 'phf-app-dcbe8.firebasestorage.app',
    iosBundleId: 'com.example.phf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwUFP0f3vCWU0C1rNqkKmfr-WG0IzIVX8',
    appId: '1:591198861834:ios:f71064d24a6af1edf17df3',
    messagingSenderId: '591198861834',
    projectId: 'phf-app-dcbe8',
    storageBucket: 'phf-app-dcbe8.firebasestorage.app',
    iosBundleId: 'com.example.phf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwPfMF-DZ6_BTNx2ygn_Q87ZQ1I4GXInY',
    appId: '1:591198861834:web:137b0f2a3fc117c9f17df3',
    messagingSenderId: '591198861834',
    projectId: 'phf-app-dcbe8',
    authDomain: 'phf-app-dcbe8.firebaseapp.com',
    storageBucket: 'phf-app-dcbe8.firebasestorage.app',
    measurementId: 'G-C4PQFDRN2D',
  );

}